# Generated by Django 2.2.7 on 2019-12-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='comment',
            field=models.CharField(max_length=150),
        ),
    ]
